### ISSUE TITLE
If a class has multiple times in one section they are not found

### ISSUE THREAD

**Issue by paisleylewis** [blerchy/schedule-scraper#1]
For example ENGR 110 has lectures that happen at different times with different professors but you sign up for both with one CRN. Your program only grabs whatever the first of these times are and not the second. 
Its really great otherwise though

**Comment by matt-lebl** [comment]
Thanks for flagging this! I have been able to reproduce the issue. It looks like fixing this will require some fundamental changes to the program, so it may take a little time. I'll get right on it.

**Comment by matt-lebl** [comment]
@VolcanicDragona I think this does it! Please let me know if you're still experiencing this issue with the new version.

**Comment by paisleylewis** [comment]
Yep that fixes it, thanks!
